# Generated by Django 5.1.1 on 2024-11-13 03:10

import django.db.models.deletion
import django.utils.timezone
import mbkmapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mk', models.CharField(max_length=255)),
                ('sks', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program', models.CharField(max_length=255)),
                ('penyelenggara', models.CharField(max_length=255)),
                ('durasi', models.CharField(max_length=64)),
                ('kuota', models.PositiveIntegerField()),
                ('deskripsi', models.TextField()),
                ('rincian_kegiatan', models.TextField()),
                ('kriteria_peserta', models.TextField()),
                ('sks', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=50, unique=True)),
                ('universitas', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_pictures/')),
                ('universitas', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=50)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('dosen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswa', to='mbkmapp.dosen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Konversi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('sedang_diverifikasi', 'Sedang Diverifikasi'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='sedang_diverifikasi', max_length=20)),
                ('ipk', models.FloatField(validators=[mbkmapp.models.validate_ipk])),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('dosen_wali', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='konversi_mahasiswa', to='mbkmapp.dosen')),
                ('mahasiswa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mbkmapp.mahasiswa')),
                ('matkul_konversi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='konversi', to='mbkmapp.matakuliah')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='konversi_program', to='mbkmapp.program')),
            ],
        ),
        migrations.CreateModel(
            name='TimKonversi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_timkonversi', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loa_file', models.FileField(blank=True, null=True, upload_to='loa_files/')),
                ('status', models.CharField(choices=[('sedang_diverifikasi', 'Sedang Diverifikasi'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='sedang_diverifikasi', max_length=20)),
                ('catatan_verifikasi', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('konversi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loa', to='mbkmapp.konversi')),
                ('tim_konversi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mbkmapp.timkonversi')),
            ],
        ),
        migrations.CreateModel(
            name='Verifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_verifikasi', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sedang_diverifikasi', 'Sedang Diverifikasi'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('dosen_wali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosen_verifikasi', to='mbkmapp.dosen')),
            ],
        ),
        migrations.AddField(
            model_name='konversi',
            name='verifikasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='konversi', to='mbkmapp.verifikasi'),
        ),
    ]
