# Generated by Django 5.1.1 on 2024-11-14 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbkmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matakuliah',
            old_name='sks',
            new_name='sks_mk',
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matkul_program', to='mbkmapp.program'),
        ),
    ]
