# Generated by Django 5.1.1 on 2024-11-14 14:41

import mbkmapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbkmapp', '0002_rename_sks_matakuliah_sks_mk_matakuliah_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='ipk',
            field=models.FloatField(null=True, validators=[mbkmapp.models.validate_ipk]),
        ),
    ]
