# Generated by Django 5.1.1 on 2024-11-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbkmapp', '0003_mahasiswa_ipk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='ipk',
            new_name='ipk_mhs',
        ),
    ]
