# Generated by Django 5.1.1 on 2024-11-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbkmapp', '0004_rename_ipk_mahasiswa_ipk_mhs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matakuliah',
            name='program',
        ),
        migrations.AddField(
            model_name='program',
            name='mata_kuliah',
            field=models.ManyToManyField(related_name='programs', to='mbkmapp.matakuliah'),
        ),
    ]
