# Generated by Django 5.1.3 on 2024-11-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbkmapp', '0005_remove_matakuliah_program_program_mata_kuliah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konversi',
            name='matkul_konversi',
        ),
        migrations.AddField(
            model_name='konversi',
            name='matkul_konversi',
            field=models.ManyToManyField(related_name='konversi', to='mbkmapp.matakuliah'),
        ),
    ]
