# Generated by Django 5.1.3 on 2024-11-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbkmapp', '0006_remove_konversi_matkul_konversi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='kode_mk',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
