# Generated by Django 5.1.3 on 2024-11-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbkmapp', '0007_matakuliah_kode_mk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konversi',
            name='ipk',
        ),
    ]
